name: tmdb_awesome
description: "Awesome TMDB"

version: 1.0.0+1
publish_to: "none"

# ----------------------------------------
# DART SDK CONSTRAINT
# ----------------------------------------
environment:
  sdk: ^3.6.2

# ----------------------------------------
# MAIN DEPENDENCIES
# ----------------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  responsive_size:
    git:
      url: https://github.com/theofficialdavlatovnizomjon/responsive_size.git

  # Local packages (internal modules)
  #  component:
  #    path: packages
  # Core utility libraries
  web: ^1.1.1
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3
  dio: ^5.8.0+1
  injectable: ^2.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.3
  go_router: ^16.0.0
  connectivity_plus: ^6.1.3
  package_info_plus: ^8.3.0
  flutter_pretty_dio_logger: ^3.0.0
  envied: ^1.1.1

  # In-app purchases
  # in_app_purchase: ^3.2.3
  # Firebase & notifications
  firebase_core: ^3.13.0
  firebase_messaging: ^15.2.5
  flutter_local_notifications: ^19.1.0

  # UI components
  flutter_svg: ^2.0.17
  pinput: ^5.0.1
  # flutter_screenutil: ^5.9.3
  smooth_page_indicator: ^1.2.1
  pull_to_refresh: ^2.0.0
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  easy_radio: ^0.0.3
  youtube_player_iframe: ^5.2.2
  calendar_date_picker2: ^2.0.1
  story_view: ^0.16.6
  mask_text_input_formatter: ^2.9.0
  cached_network_image: ^3.4.1
  permission_handler: ^12.0.0+1

  # Code generation annotations
  freezed_annotation: ^2.4.1
  built_value: ^8.6.3
  built_collection: ^5.1.1
  intl: ^0.20.2
  flutter_html: ^3.0.0
  path_provider: ^2.1.5
  injectable_generator: ^2.6.1

# ----------------------------------------
# DEVELOPMENT DEPENDENCIES
# ----------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Code generation tools
  build_runner: ^2.4.11
  built_value_generator: ^8.6.3
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_gen_runner: ^5.10.0
  envied_generator: ^1.1.1
  # Optional: app launcher icon generation
  # flutter_launcher_icons: ^0.14.3

# ----------------------------------------
# FLUTTER CONFIGURATION
# ----------------------------------------
flutter:
  uses-material-design: true
  generate: true

  # Asset directories
  assets:
    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logo/
    - assets/mock/
    - assets/translate/

  # Custom font configuration
  # fonts:
  #   - family: Manrope
  #     fonts:
  #       - asset: assets/fonts/extra-bold.ttf
  #         weight: 800
  #       - asset: assets/fonts/bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/semi-bold.ttf
  #         weight: 600
  #       - asset: assets/fonts/medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/regular.ttf
  #         weight: 400
  #       - asset: assets/fonts/light.ttf
  #         weight: 300
  #       - asset: assets/fonts/extra-light.ttf
  #         weight: 200
  fonts:
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope/Manrope-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Manrope/Manrope-Bold.ttf
          weight: 700
        - asset: assets/fonts/Manrope/Manrope-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Manrope/Manrope-Medium.ttf
          weight: 500
        - asset: assets/fonts/Manrope/Manrope-Regular.ttf
          weight: 400
        - asset: assets/fonts/Manrope/Manrope-Light.ttf
          weight: 300

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/Inter-Light.ttf
          weight: 300

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300

    - family: Mont
      fonts:
        - asset: assets/fonts/Mont/Mont-Black.ttf
          weight: 900
        - asset: assets/fonts/Mont/Mont-Heavy.ttf
          weight: 800
        - asset: assets/fonts/Mont/Mont-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mont/Mont-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Mont/Mont-Regular.ttf
          weight: 400
        - asset: assets/fonts/Mont/Mont-Light.ttf
          weight: 300

# ----------------------------------------
# FLUTTER GEN CONFIGURATION
# ----------------------------------------
flutter_gen:
  output: lib/src/generated/
  line_length: 120
  integrations:
    flutter_svg: true
flutter_intl:
  enabled: true
