name: ui
description: >
  A simple and lightweight Flutter package for responsive design using screen width and height extensions.
version: 0.0.1
publish_to: "none"
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
